.PHONY: help install lint test validate check clean

help:
	@echo "Targets:"
	@echo "  install   install dependencies from requirements.txt"
	@echo "  lint      run ruff"
	@echo "  test      run the full test suite"
	@echo "  validate  run the CPU correctness checks (convergence + variance)"
	@echo "  check     lint, test, and validate (what CI runs)"
	@echo "  clean     remove caches and generated bytecode"

install:
	pip install -r requirements.txt

lint:
	ruff check .

test:
	pytest -q

validate:
	python validate.py

check: lint test validate

clean:
	rm -rf .pytest_cache .ruff_cache
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
